### ISSUE TITLE
main page have duplicated

### ISSUE THREAD

**Issue by progreccor** [SPQRInc/pagekit-sitemap#1]
I have tried to generate sitemap with your extension and see the main page twice in the xml file,
http://www.zoloto-pokupka.ru/sitemap.xml

**Comment by ahoiroman** [comment]
I will have a look at it- thanks for your report.

**Comment by ahoiroman** [comment]
Hello,

I was not able to reproduce this error on my 5 testing-sites. But nevertheless I fixed an error, which could possibly lead to such an behavior, so you could update the extension using your pagekit-backend.

If the error is still present it would be great if you could report this again.

**Comment by progreccor** [comment]
I have updated your extension and regenerated the sitemap

But dublicated entry still there....

I can give you admin entry to the site if it help you

I have very simple site, only some static pages and thats all...

![2017-03-17_12-23-52](https://cloud.githubusercontent.com/assets/3103677/24036879/aa85b4de-0b0c-11e7-8e7b-2475c94599c5.png)

**Comment by ahoiroman** [comment]
Would help. Please contact me via e-mail or private chat on gitter.im.

**Comment by progreccor** [comment]
can't find your email so write you at gitter

**Comment by ahoiroman** [comment]
Should be closed with version 1.0.4. Please update via marketplace and update this issue.

**Comment by progreccor** [comment]
After updating to the latest version all is ok.
There are now duplicates!
