### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by jack-theripper** [SPQRInc/pagekit-sitemap#2]
Hi. Thank you for your module.

> Fatal error: Call to a member function find() on boolean in <...>\packages\spqr\sitemap\src\Helper\SitemapHelper.php on line 172

at `SitemapHelper->scan() in SitemapHelper.php line 224`

I think the script tries to download a file (e.g. pdf or excel) and it breaks all

**Comment by ahoiroman** [comment]
Hm, the script should not even care about PDF or excel. I guess I would have to debug this.

It seems that `HtmlDomParser::str_get_html( $this->getURL( $url ) ); ` does not return the expected value for some reason.

Is there any (broken) sitemap generated at all?

**Comment by jack-theripper** [comment]
Yes, the other online service generates a perfect sitemap. 

I make small fix, but `HtmlDomParser::str_get_html( $this->getURL( $url ) );` continues to download files via links. this is normal?

```php
if ($html === false) {
return ;
}
```

**Comment by ahoiroman** [comment]
Hm, it should not do this. I will double-check it. 

The extension-check should just call the function recursively if the extension of the file is found in the array of allowed extensions. Which filetype is the worker downloading in your case?

**Comment by ahoiroman** [comment]
In all my tests the crawler crawled only the defined extensions. Could you please tell me, which file format the extensions have?

**Comment by jack-theripper** [comment]
There is no format extension, just a link (for example `http://site.ru/download/123` or `http://site.ru/<.. slug >/download`). This is not html content so error in function `str_get_html`

**Comment by ahoiroman** [comment]
Thanks a lot - now I understand why the extension-check did not work in your case. I also created a check for this and added a general check if `$html` is valid or not (as you suggested).

This is already included in `1.0.7` which is downloadable from the marketplace.

**Comment by jack-theripper** [comment]
thanks
