### ISSUE TITLE
Restrict display of main menu item

### ISSUE THREAD

**Issue by tobbexiv** [SPQRInc/pagekit-sitemap#3]
Please do also add the `'access' => 'sitemap: manage settings'` property for the main menu item [`sitemap`](https://github.com/SPQRInc/pagekit-sitemap/blob/master/index.php#L29). Now, if a user has no access, the icon is still displayed but an error message appears as soon as the user clicks on it. As the item has no functionality for a user without access, it should also not be displayed.

Reproduce:
Create a user without sitemap rights and logon to it. You still see the icon even if you cannot do anything with it.

**Comment by ahoiroman** [comment]
I‘ll add this and release the fix with the next update.

Thank you for the hint :)

**Comment by ahoiroman** [comment]
Fixed with version `1.0.9`.
