### ISSUE TITLE
generate button produces 404 error

### ISSUE THREAD

**Issue by robwelan** [SPQRInc/pagekit-sitemap#4]
pagekit version: 1.0.13
error: POST http://localhost:8888/admin/sitemap/generate 404 (Not Found)

Occurs when pressing the Generate button.

**Comment by ahoiroman** [comment]
Hm, I tested it and can not confirm that. Please have a look at the routing, whether the routing is registered correctly.

Which version are you using?

![bildschirmfoto 2017-12-15 um 06 40 24](https://user-images.githubusercontent.com/23051150/34028371-dc3f3d4c-e162-11e7-9394-c2c6c0babc0e.png)


P.S. Clicking the button should **not** reload the page or redirect to another page. The generation-process is supposed to run in the background using Ajax.

**Comment by ahoiroman** [comment]
As there's no response, please reopen, if the error occurs with the current version `1.0.10`, too.
