### ISSUE TITLE
Generate issues

### ISSUE THREAD

**Issue by mzulfahmy** [SPQRInc/pagekit-sitemap#5]
Hi,

I'm having difficulties to generate my sitemap and it contain some error

https://blog.zulfahmy.net/sitemap.xml

Thank you

**Comment by ahoiroman** [comment]
Please enable Pagekit's debug mode and open the browsers network connections screen. Click the "Generate" button  and check the response of `/generate`.

**Comment by mzulfahmy** [comment]
Hi, It seems the issues comes from curl

Currently my blog is hosted under a VPS and protected on Cloudflare.

![11](https://user-images.githubusercontent.com/4937448/45007071-8ddf3580-b02e-11e8-9e61-8076daa6b370.PNG)

**Comment by mzulfahmy** [comment]
Also, 

I have disabled CSF firewall from my server, the same error occurs.

**Comment by ahoiroman** [comment]
Well - cURL can not resolve the hostname. So please check, whether your VPS is able to resolve this hostname. Actually - at the moment - the `dig` throws back a cloudflare-IP, but this is no necessarily the problem.

**Comment by mzulfahmy** [comment]
Hi @SPQRInc ,

I was able to curl after disabling my CSF and rebooted my server once.

However, the sitemap.xml is not updated and throwing out error 
https://blog.zulfahmy.net/sitemap.xml

![13](https://user-images.githubusercontent.com/4937448/45072353-28ae4180-b10d-11e8-9909-12466142c554.PNG)
![14](https://user-images.githubusercontent.com/4937448/45072354-2ba93200-b10d-11e8-97aa-ba8da97b7dae.PNG)

**Comment by ahoiroman** [comment]
Could you please copy and paste the full debug-log?

**Comment by mzulfahmy** [comment]
Hi,

Here the long list for the error.

https://zulfahmy.net/error.txt

I think memory exhausted from "?C=N;O=D?C=N;O=A?C=N;O" url

**Comment by ahoiroman** [comment]
Yes, the extension seems to try to call a file from `/downloads`. 

You could add an exclusion (for URL and/or extensions).

**Comment by mzulfahmy** [comment]
Hi @SPQRInc 

Thank you for sorting out the issues.

I have added the exclusion to /downloads folder and now the plugins starts working.

**Comment by ahoiroman** [comment]
Great :-) So I am closing this issue :-)
